
server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master #\u4E0D\u5199\u9ED8\u8BA4\u662Fmaster
      server:
        git:
          uri: https://github.com/huiyunfei/spring-cloud
          search-paths: /cloud-config/**  # \u6307\u5B9A\u641C\u7D22\u6839\u8DEF\u5F84\u4E0B\u7684\u6240\u6709\u76EE\u5F55\uFF0C\u82E5\u6709\u591A\u4E2A\u8DEF\u5F84\u4F7F\u7528\u9017\u53F7\u9694\u5F00 cloud-config
          username:
          password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/